language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amattus/docker-react -f Dockerfile.dev .

script:
  - docker run amattus/docker-react npm run test -- --coverage